# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: api-gateway
#   namespace: microservices
#   labels:
#     app: api-gateway
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   ingressClassName: nginx
#   rules:
#     - http:
#         paths:
#           # backend only for now (add frontend paths here later)
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: api-gateway
#                 port:
#                   number: 3000
