kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    # ตั้ง label ให้ ingress-nginx (kind variant) เลือกลง node นี้ได้
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    # เจาะ port 80/443 จาก host (Mac) เข้าไปที่ node container
    # เพื่อให้เข้า http://localhost / https://localhost ได้โดยไม่ต้อง port-forward
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
